/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.fikuro.futsalscoreboard.forms;

import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Jussi Seppälä
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        team2Faults = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        team1Faults = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        team1ScorePlus = new javax.swing.JButton();
        team2ScorePlus = new javax.swing.JButton();
        team1ScoreMinus = new javax.swing.JButton();
        team2ScoreMinus = new javax.swing.JButton();
        team1FaultPlus = new javax.swing.JButton();
        team1FaultMinus = new javax.swing.JButton();
        team2FaultPlus = new javax.swing.JButton();
        team2FaultMinus = new javax.swing.JButton();
        minutes = new javax.swing.JLabel();
        team1Name = new javax.swing.JTextField();
        team2Name = new javax.swing.JTextField();
        cmdUpdateTeam1Name = new javax.swing.JButton();
        cmdUpdateTeam2Name = new javax.swing.JButton();
        cmdMinutesPlus = new javax.swing.JButton();
        cmdMinutesMinus = new javax.swing.JButton();
        minutesPostfix = new javax.swing.JLabel();
        txtHalf = new javax.swing.JTextField();
        updateHalf = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHalf = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        team1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        team1Score = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        team2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        team2Score = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        teamSeparator = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fikuro Futsal Scoreboard");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        team2Faults.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        team2Faults.setForeground(new java.awt.Color(255, 0, 0));
        team2Faults.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        getContentPane().add(team2Faults, gridBagConstraints);

        jLabel2.setText("            ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel2, gridBagConstraints);

        team1Faults.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        team1Faults.setForeground(new java.awt.Color(255, 0, 0));
        team1Faults.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        getContentPane().add(team1Faults, gridBagConstraints);

        jLabel1.setText("            ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jLabel1, gridBagConstraints);

        team1ScorePlus.setText("Score+");
        team1ScorePlus.setActionCommand("team1ScorePlus");
        team1ScorePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1ScorePlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(team1ScorePlus, gridBagConstraints);

        team2ScorePlus.setText("Score+");
        team2ScorePlus.setActionCommand("team2ScorePlus");
        team2ScorePlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2ScorePlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        getContentPane().add(team2ScorePlus, gridBagConstraints);

        team1ScoreMinus.setText("Score-");
        team1ScoreMinus.setActionCommand("team1ScoreMinus");
        team1ScoreMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1ScoreMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        getContentPane().add(team1ScoreMinus, gridBagConstraints);

        team2ScoreMinus.setText("Score-");
        team2ScoreMinus.setActionCommand("team2ScoreMinus");
        team2ScoreMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2ScoreMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        getContentPane().add(team2ScoreMinus, gridBagConstraints);

        team1FaultPlus.setText("Fault+");
        team1FaultPlus.setActionCommand("team1FaultPlus");
        team1FaultPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1FaultPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        getContentPane().add(team1FaultPlus, gridBagConstraints);

        team1FaultMinus.setText("Fault-");
        team1FaultMinus.setActionCommand("team1FaultMinus");
        team1FaultMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team1FaultMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        getContentPane().add(team1FaultMinus, gridBagConstraints);

        team2FaultPlus.setText("Fault+");
        team2FaultPlus.setActionCommand("team2FaultPlus");
        team2FaultPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2FaultPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        getContentPane().add(team2FaultPlus, gridBagConstraints);

        team2FaultMinus.setText("Fault-");
        team2FaultMinus.setActionCommand("team2FaultMinus");
        team2FaultMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                team2FaultMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 9;
        getContentPane().add(team2FaultMinus, gridBagConstraints);

        minutes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minutes.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(minutes, gridBagConstraints);

        team1Name.setText("Josepa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(team1Name, gridBagConstraints);

        team2Name.setText("Leijona");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(team2Name, gridBagConstraints);

        cmdUpdateTeam1Name.setText("Update");
        cmdUpdateTeam1Name.setActionCommand("cmdUpdateTeam1Name");
        cmdUpdateTeam1Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateTeam1NameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        getContentPane().add(cmdUpdateTeam1Name, gridBagConstraints);

        cmdUpdateTeam2Name.setText("Update");
        cmdUpdateTeam2Name.setActionCommand("cmdUpdateTeam2Name");
        cmdUpdateTeam2Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUpdateTeam2NameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 7;
        getContentPane().add(cmdUpdateTeam2Name, gridBagConstraints);

        cmdMinutesPlus.setText("Minutes+");
        cmdMinutesPlus.setActionCommand("cmdMinutesPlus");
        cmdMinutesPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinutesPlusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        getContentPane().add(cmdMinutesPlus, gridBagConstraints);

        cmdMinutesMinus.setText("Minutes-");
        cmdMinutesMinus.setActionCommand("cmdMinutesMinus");
        cmdMinutesMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMinutesMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        getContentPane().add(cmdMinutesMinus, gridBagConstraints);

        minutesPostfix.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        minutesPostfix.setText("'");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        getContentPane().add(minutesPostfix, gridBagConstraints);

        txtHalf.setText("1.puoliaika");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(txtHalf, gridBagConstraints);

        updateHalf.setText("Update");
        updateHalf.setActionCommand("updateHalf");
        updateHalf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateHalfActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        getContentPane().add(updateHalf, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblHalf.setText("1.puoliaika");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(lblHalf, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        team1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        team1.setForeground(new java.awt.Color(255, 255, 255));
        team1.setText(" Josepa ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(team1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        team1Score.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        team1Score.setForeground(new java.awt.Color(255, 255, 255));
        team1Score.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(team1Score, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        team2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        team2.setForeground(new java.awt.Color(255, 255, 255));
        team2.setText("Leijona");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel4.add(team2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        team2Score.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        team2Score.setForeground(new java.awt.Color(255, 255, 255));
        team2Score.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel5.add(team2Score, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel5, gridBagConstraints);

        jPanel6.setLayout(new java.awt.GridBagLayout());

        teamSeparator.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        teamSeparator.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel6.add(teamSeparator, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel6, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdUpdateTeam1NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateTeam1NameActionPerformed
        // TODO add your handling code here:
        team1.setText(team1Name.getText());
    }//GEN-LAST:event_cmdUpdateTeam1NameActionPerformed

    private void cmdUpdateTeam2NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUpdateTeam2NameActionPerformed
        team2.setText(team2Name.getText());
    }//GEN-LAST:event_cmdUpdateTeam2NameActionPerformed

    private void team1ScorePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1ScorePlusActionPerformed
        Integer score = Integer.parseInt( team1Score.getText()) + 1;
        team1Score.setText(score.toString());
    }//GEN-LAST:event_team1ScorePlusActionPerformed

    private void team2ScorePlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2ScorePlusActionPerformed
        Integer score = Integer.parseInt( team2Score.getText()) + 1;
        team2Score.setText(score.toString());
    }//GEN-LAST:event_team2ScorePlusActionPerformed

    private void team1ScoreMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1ScoreMinusActionPerformed
        Integer score = Integer.parseInt( team1Score.getText()) - 1;
        team1Score.setText(score.toString());
    }//GEN-LAST:event_team1ScoreMinusActionPerformed

    private void team2ScoreMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2ScoreMinusActionPerformed
        Integer score = Integer.parseInt( team2Score.getText()) - 1;
        team2Score.setText(score.toString());
    }//GEN-LAST:event_team2ScoreMinusActionPerformed

    private void team1FaultPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1FaultPlusActionPerformed
        Integer faults = Integer.parseInt( team1Faults.getText()) + 1;
        team1Faults.setText(faults.toString());
    }//GEN-LAST:event_team1FaultPlusActionPerformed

    private void team2FaultPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2FaultPlusActionPerformed
        Integer faults = Integer.parseInt( team2Faults.getText()) + 1;
        team2Faults.setText(faults.toString());
    }//GEN-LAST:event_team2FaultPlusActionPerformed

    private void team1FaultMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team1FaultMinusActionPerformed
        Integer faults = Integer.parseInt( team1Faults.getText()) - 1;
        team1Faults.setText(faults.toString());
    }//GEN-LAST:event_team1FaultMinusActionPerformed

    private void team2FaultMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_team2FaultMinusActionPerformed
        Integer faults = Integer.parseInt( team2Faults.getText()) - 1;
        team2Faults.setText(faults.toString());
    }//GEN-LAST:event_team2FaultMinusActionPerformed

    private void cmdMinutesPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinutesPlusActionPerformed
        Integer mins = Integer.parseInt( minutes.getText()) + 1;
        minutes.setText(mins.toString());
    }//GEN-LAST:event_cmdMinutesPlusActionPerformed

    private void cmdMinutesMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMinutesMinusActionPerformed
        Integer mins = Integer.parseInt( minutes.getText()) - 1;
        minutes.setText(mins.toString());
    }//GEN-LAST:event_cmdMinutesMinusActionPerformed

    private void updateHalfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateHalfActionPerformed
        // TODO add your handling code here:
        lblHalf.setText(txtHalf.getText());
    }//GEN-LAST:event_updateHalfActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JRootPane rootPane = SwingUtilities.getRootPane(cmdMinutesPlus); 
        rootPane.setDefaultButton(cmdMinutesPlus);
        
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdMinutesMinus;
    private javax.swing.JButton cmdMinutesPlus;
    private javax.swing.JButton cmdUpdateTeam1Name;
    private javax.swing.JButton cmdUpdateTeam2Name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblHalf;
    private javax.swing.JLabel minutes;
    private javax.swing.JLabel minutesPostfix;
    private javax.swing.JLabel team1;
    private javax.swing.JButton team1FaultMinus;
    private javax.swing.JButton team1FaultPlus;
    private javax.swing.JLabel team1Faults;
    private javax.swing.JTextField team1Name;
    private javax.swing.JLabel team1Score;
    private javax.swing.JButton team1ScoreMinus;
    private javax.swing.JButton team1ScorePlus;
    private javax.swing.JLabel team2;
    private javax.swing.JButton team2FaultMinus;
    private javax.swing.JButton team2FaultPlus;
    private javax.swing.JLabel team2Faults;
    private javax.swing.JTextField team2Name;
    private javax.swing.JLabel team2Score;
    private javax.swing.JButton team2ScoreMinus;
    private javax.swing.JButton team2ScorePlus;
    private javax.swing.JLabel teamSeparator;
    private javax.swing.JTextField txtHalf;
    private javax.swing.JButton updateHalf;
    // End of variables declaration//GEN-END:variables
}
